import Link from 'next/link';
import type { Metadata } from 'next';

export default function Page() {
  return (
    <div className="space-y-4">
      <h1 className="text-xl font-semibold">Test 2 page</h1>
      <Link href="/test-1" className="underline">
        Test 1
      </Link>
    </div>
  );
}

export const metadata: Metadata = {
  title: 'Test 2',
  description: 'Generated by Test 2',
};
