import Link from 'next/link';
import type { Metadata } from 'next';

export default function Page() {
  return (
    <div className="space-y-4">
      <h1 className="text-xl font-semibold">Test 1 page</h1>
      <Link href="/test-2" className="underline">
        Test 2
      </Link>
    </div>
  );
}

export const metadata: Metadata = {
  title: 'Test 1',
  description: 'Generated by Test 1',
};
